### PR TITLE
prevent leaking "error" to global scope

### PR DESCRIPTION
**Pull request by fjakobs**

### CODE REVIEW

**Comment by brettlangdon** [comment]
good catch, thank you.

**Comment by fjakobs** [comment]
@brettlangdon thanks for pulling it in. Would you mind bumping the version number and publishing it to NPM? This was failing one of my mocha tests.

**Comment by brettlangdon** [comment]
Yup, can do, as soon as well im back in front of a computer.

**Comment by fjakobs** [comment]
Awesome. Thanks

**Comment by brettlangdon** [comment]
done.

**Comment by fjakobs** [comment]
that's how open source should work :-)

**Pull request merged**
