### PR TITLE
Use "count" as metric type instead of "counter" in the docs

### PR DESCRIPTION
**Pull request by jetmind**
This is the right value as seen here https://github.com/brettlangdon/node-dogapi/issues/35#issuecomment-198357491

### CODE REVIEW

**Comment by brettlangdon** [comment]
Hmm, it is weird that the docs for the Python client say "counter" https://github.com/DataDog/datadogpy/blob/55bf806eef399e0f60204ede61a962e591c8ee5a/datadog/api/metrics.py#L83

**Comment by jetmind** [comment]
Yeah, but when I set it to counter I get gauge in the datadog dashboard, but count works as expected.

**Comment by brettlangdon** [comment]
hmm... I just tested and confirmed, you are correct, however, for this change we need to update `s/counter/count/` in a few other places as well.

In order to update the docs, we actually have to update the doc strings in the code. The `index.html` is generated on release, so you won't need to update `index.html`.

We will want to update `lib/api/metric.js` to reference `count` in the doc strings/examples: https://github.com/brettlangdon/node-dogapi/blob/79226c9037dd8d58bc53ed689110c6aa19fa28d7/lib/api/metric.js

And then update `test/api/metric.js` to use `count` instead of `counter`: https://github.com/brettlangdon/node-dogapi/blob/79226c9037dd8d58bc53ed689110c6aa19fa28d7/test/api/metric.js

**Comment by brettlangdon** [comment]
Thanks for catching this bug.

**Comment by jetmind** [comment]
Created a new pull request https://github.com/brettlangdon/node-dogapi/pull/38

Closing this.

**Pull request closed without merging**
