### PR TITLE
use os.EOL to determine platform line ending

### PR DESCRIPTION
**Pull request by jrgm**
A minor itch, if it's of use

### CODE REVIEW

**Comment by jrgm** [comment]
Which goes back to 0.8, and is just '\r\n' on win32, otherwise '\n'.

**Comment by brettlangdon** [comment]
looks good to me, thanks for the contribution!

**Comment by brettlangdon** [comment]
version `2.2.1` is now published with these changes.

**Comment by jrgm** [comment]
Glad to help. Thanks for this module. Look forward to making more use of this.

**Pull request merged**
