### PR TITLE
Added IPv6 support.

### PR DESCRIPTION
**Pull request by Townsheriff**
Exposing http options for IPv6 support.

### CODE REVIEW

**Comment by brettlangdon** [comment]
@Townsheriff looks great!

The commit history looks a little weird, happen to know what happened?

**Comment by Townsheriff** [comment]
@brettlangdon Looks like I forked wrong branch. Let me try to fix it.

**Comment by brettlangdon** [comment]
awesome, thanks for cleaning that up!

I'll release now.

**Comment by brettlangdon** [comment]
@Townsheriff v2.6.0 is now published to npm.

Thanks again for the contribution!

**Pull request merged**
